<?xml version="1.0" encoding="UTF-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <BasePath>$(MSBuildThisFileDirectory)</BasePath>
    <ArtifactsDir>$(BasePath)\artifacts\</ArtifactsDir>
    <BaseIntermediateOutputPath>$(ArtifactsDir)obj\$(MSBuildProjectName)\</BaseIntermediateOutputPath>
    <BaseOutputPath>$(ArtifactsDir)bin\$(MSBuildProjectName)\</BaseOutputPath>
    <PackageOutputPath>$(ArtifactsDir)nuget\$(Configuration)\</PackageOutputPath>
  </PropertyGroup>
  <PropertyGroup>
    <PackageTargetFrameworks>net462;net10.0-windows10.0.19041.0</PackageTargetFrameworks>
    <SampleTargetFrameworks>net462;net10.0-windows10.0.19041.0</SampleTargetFrameworks>
    <TestTargetFrameworks>net462;net10.0-windows10.0.19041.0</TestTargetFrameworks>
    <PackageVersion>2.0.0</PackageVersion>
  </PropertyGroup>
</Project>
